name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Jalankan pipeline saat ada perubahan di branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t rotua1005/contoh-wayang:latest .

      # Push Docker image ke Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push rotua1005/contoh-wayang:latest
